###install package tidyverse if not already installed

```{r}
if(!require(tidyverse)){ install.packages("tidyverse") }  
library("tidyverse") 
infile1 <- trimws("https://pasta.lternet.edu/package/data/eml/edi/705/5/1c3181f05aab7420182a14851f916ef3") 
infile1 <-sub("^https","http",infile1)
```

### This creates a tibble named: dt1 

```{r}
dt1 <-read_delim(infile1  
                 ,delim=","   
                 ,skip=1 
                 ,quote='"'  
                 , col_names=c( 
                   "SiteID",   
                   "LakeID",   
                   "LakeName",   
                   "Date",   
                   "Depth_m",   
                   "Temperature_degCelsius"   ), 
                 col_types=list(
                   col_number() , 
                   col_number() ,  
                   col_character(),  
                   col_date("%Y-%m-%d"),  
                   col_number() , 
                   col_number() ), 
                 na=c(" ",".","NA","")  )
# Convert Missing Values to NA for individual vectors 
dt1$Temperature_degCelsius <- ifelse((trimws(as.character(dt1$Temperature_degCelsius))==trimws("NA")),NA,dt1$Temperature_degCelsius)               
suppressWarnings(dt1$Temperature_degCelsius <- ifelse(!is.na(as.numeric("NA")) & (trimws(as.character(dt1$Temperature_degCelsius))==as.character(as.numeric("NA"))),NA,dt1$Temperature_degCelsius))

```

###Inspect tibble dt1

```{r}
# Observed issues when reading the data. An empty list is good!
problems(dt1) 
# Here is the structure of the input data tibble: 
glimpse(dt1) 
# And some statistical summaries of the data 
summary(dt1) 
# Get more details on character variables

summary(as.factor(dt1$LakeName)) 
infile2 <- trimws("https://pasta.lternet.edu/package/data/eml/edi/705/5/1e5e05e46c3094d2d368a798eae22cbf") 
infile2 <-sub("^https","http",infile2)

```

### This creates a tibble named: dt2 

```{r}
dt2 <-read_delim(infile2  
                 ,delim=","   
                 ,skip=1 
                 ,quote='"'  
                 , col_names=c( 
                   "SiteID",   
                   "LakeID",   
                   "LakeName",   
                   "Date",   
                   "Depth_m",   
                   "Temperature_degCelsius"   ), 
                 col_types=list(
                   col_number() , 
                   col_number() ,  
                   col_character(),  
                   col_date("%Y-%m-%d"),  
                   col_number() , 
                   col_number() ), 
                 na=c(" ",".","NA","")  )


# Convert Missing Values to NA for individual vectors 
dt2$Temperature_degCelsius <- ifelse((trimws(as.character(dt2$Temperature_degCelsius))==trimws("NA")),NA,dt2$Temperature_degCelsius)               
suppressWarnings(dt2$Temperature_degCelsius <- ifelse(!is.na(as.numeric("NA")) & (trimws(as.character(dt2$Temperature_degCelsius))==as.character(as.numeric("NA"))),NA,dt2$Temperature_degCelsius))

```

### Inspect tibble dt2

```{r}
# Observed issues when reading the data. An empty list is good!
problems(dt2) 
# Here is the structure of the input data tibble: 
glimpse(dt2) 
# And some statistical summaries of the data 
summary(dt2) 
# Get more details on character variables

summary(as.factor(dt2$LakeName)) 
infile3 <- trimws("https://pasta.lternet.edu/package/data/eml/edi/705/5/974aa15895f4d691edd7a9dcb0ab4457") 
infile3 <-sub("^https","http",infile3)

```

### This creates a tibble named dt3 that contains site information

```{r}
dt3 <-read_delim(infile3  
                 ,delim=","   
                 ,skip=1 
                 ,quote='"'  
                 , col_names=c( 
                   "SiteID",   
                   "LakeID",   
                   "LakeName",   
                   "AlternateLakeName",   
                   "LakeOrReservoir",   
                   "CountryOfLake",   
                   "Region",   
                   "Latitude",   
                   "Longitude",   
                   "Elevation_m",   
                   "SurfaceArea_km2",   
                   "Volume_km3",   
                   "MaxDepth_m",   
                   "MeanDepth_m",   
                   "Secchi_m",   
                   "Chlorophyll_ug_L",   
                   "TotalPhosphorus_ug_L",   
                   "DissolvedOrganicCarbon_mg_L",   
                   "Contributor",   
                   "ContributorContact",   
                   "ContributorInstitution"   ), 
                 col_types=list(
                   col_number() , 
                   col_number() ,  
                   col_character(),  
                   col_character(),  
                   col_character(),  
                   col_character(),  
                   col_character(), 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() , 
                   col_number() ,  
                   col_character(),  
                   col_character(),  
                   col_character()), 
                 na=c(" ",".","NA","")  )


# Convert Missing Values to NA for individual vectors 
dt3$Elevation_m <- ifelse((trimws(as.character(dt3$Elevation_m))==trimws("NA")),NA,dt3$Elevation_m)               
suppressWarnings(dt3$Elevation_m <- ifelse(!is.na(as.numeric("NA")) & (trimws(as.character(dt3$Elevation_m))==as.character(as.numeric("NA"))),NA,dt3$Elevation_m))
dt3$SurfaceArea_km2 <- ifelse((trimws(as.character(dt3$SurfaceArea_km2))==trimws("NA")),NA,dt3$SurfaceArea_km2)               
suppressWarnings(dt3$SurfaceArea_km2 <- ifelse(!is.na(as.numeric("NA")) & (trimws(as.character(dt3$SurfaceArea_km2))==as.character(as.numeric("NA"))),NA,dt3$SurfaceArea_km2))
dt3$Volume_km3 <- ifelse((trimws(as.character(dt3$Volume_km3))==trimws("NA")),NA,dt3$Volume_km3)               
suppressWarnings(dt3$Volume_km3 <- ifelse(!is.na(as.numeric("NA")) & (trimws(as.character(dt3$Volume_km3))==as.character(as.numeric("NA"))),NA,dt3$Volume_km3))
dt3$MaxDepth_m <- ifelse((trimws(as.character(dt3$MaxDepth_m))==trimws("NA")),NA,dt3$MaxDepth_m)               
suppressWarnings(dt3$MaxDepth_m <- ifelse(!is.na(as.numeric("NA")) & (trimws(as.character(dt3$MaxDepth_m))==as.character(as.numeric("NA"))),NA,dt3$MaxDepth_m))
dt3$MeanDepth_m <- ifelse((trimws(as.character(dt3$MeanDepth_m))==trimws("NA")),NA,dt3$MeanDepth_m)               
suppressWarnings(dt3$MeanDepth_m <- ifelse(!is.na(as.numeric("NA")) & (trimws(as.character(dt3$MeanDepth_m))==as.character(as.numeric("NA"))),NA,dt3$MeanDepth_m))
dt3$Secchi_m <- ifelse((trimws(as.character(dt3$Secchi_m))==trimws("NA")),NA,dt3$Secchi_m)               
suppressWarnings(dt3$Secchi_m <- ifelse(!is.na(as.numeric("NA")) & (trimws(as.character(dt3$Secchi_m))==as.character(as.numeric("NA"))),NA,dt3$Secchi_m))
dt3$Chlorophyll_ug_L <- ifelse((trimws(as.character(dt3$Chlorophyll_ug_L))==trimws("NA")),NA,dt3$Chlorophyll_ug_L)               
suppressWarnings(dt3$Chlorophyll_ug_L <- ifelse(!is.na(as.numeric("NA")) & (trimws(as.character(dt3$Chlorophyll_ug_L))==as.character(as.numeric("NA"))),NA,dt3$Chlorophyll_ug_L))
dt3$TotalPhosphorus_ug_L <- ifelse((trimws(as.character(dt3$TotalPhosphorus_ug_L))==trimws("NA")),NA,dt3$TotalPhosphorus_ug_L)               
suppressWarnings(dt3$TotalPhosphorus_ug_L <- ifelse(!is.na(as.numeric("NA")) & (trimws(as.character(dt3$TotalPhosphorus_ug_L))==as.character(as.numeric("NA"))),NA,dt3$TotalPhosphorus_ug_L))
dt3$DissolvedOrganicCarbon_mg_L <- ifelse((trimws(as.character(dt3$DissolvedOrganicCarbon_mg_L))==trimws("NA")),NA,dt3$DissolvedOrganicCarbon_mg_L)               
suppressWarnings(dt3$DissolvedOrganicCarbon_mg_L <- ifelse(!is.na(as.numeric("NA")) & (trimws(as.character(dt3$DissolvedOrganicCarbon_mg_L))==as.character(as.numeric("NA"))),NA,dt3$DissolvedOrganicCarbon_mg_L))

```

### Inspect dt3

```{r}
# Observed issues when reading the data. An empty list is good!
problems(dt3) 
# Here is the structure of the input data tibble: 
glimpse(dt3) 
# And some statistical summaries of the data 
summary(dt3) 
# Get more details on character variables

summary(as.factor(dt3$LakeName)) 
summary(as.factor(dt3$AlternateLakeName)) 
summary(as.factor(dt3$LakeOrReservoir)) 
summary(as.factor(dt3$CountryOfLake)) 
summary(as.factor(dt3$Region)) 
summary(as.factor(dt3$Contributor)) 
summary(as.factor(dt3$ContributorContact)) 
summary(as.factor(dt3$ContributorInstitution))

```

