---
title: "East Fork Creek vs Mill Creek vs Harpeth River"
output:
  html_document:
    df_print: paged
---

```{r}
# setwd("C:/Users/ayersj.VANDERBILT/OneDrive - Vanderbilt/Projects/HarpethRiver/MillCreek")
if (!require("pacman"))
   install.packages("pacman")
pacman::p_load(tidyverse, skimr,leaflet, htmltools)
Sites <- read_csv("StreamSites.csv")
Data <- read_csv("EFCvsMCvsHR_CompleteV3.csv")
skim(Data)
Data$logP <- log10(Data$P)
Species <- c("logP", "NO3")
DataParams <- Data %>%
  select(Stream, all_of(Species))
DataLong <- DataParams %>%
  gather(Species, key = "Species", value = "Concentration") %>%
  unite("Species_Stream", Species:Stream, remove = FALSE)

```

```{r}
p <- ggplot(DataLong, aes(x = Species_Stream, y = Concentration, fill = Stream)) +
              theme_bw() +
              geom_boxplot(na.rm = TRUE) +
              stat_n_text() +
              ylab("Concentration (mg/L)")
print(p)
ggsave("NutrientComparison.png",  width = 2000, height = 2*618, units = "px", plot = p)

```

### Map of site location

```{r Map}
m <- leaflet(Sites) %>% addMarkers(lat = ~Latitude, lng = ~Longitude, popup = ~htmlEscape(SiteName)) %>% 
  addProviderTiles(providers$Esri.NatGeoWorldMap)
# See http://leaflet-extras.github.io/leaflet-providers/preview/index.html
m
```


```{r}
library(psych)
myvars <- c("P", "NO3")
describeBy(Data[myvars], list(Stream = Data$Stream))
# mystats <- function(x,na.omit=FALSE){
#   if(na.omit)
#     x<-x[!is.na(x)]
#   m<-mean(x)
#   n<-length(x)
#   s<-sd(x)
#   return(c(n=n,mean=m,stdev=s))
#   }
# Robert Kabacoff. R in Action, Second Edition: Data analysis and graphics with R (Kindle Locations 3330-3334). Manning Publications. Kindle Edition. 
# dstats <- function(x)sapply(x, mystats)
# myvars <- c("P", "NO3")
# by(Data[myvars], Data$Stream, dstats)

```

